//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPRM.SAP.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recurso {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recurso() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TPRM.SAP.Web.App_GlobalResources.Recurso", typeof(Recurso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro foi alterado com sucesso..
        /// </summary>
        public static string AlteradoSucesso {
            get {
                return ResourceManager.GetString("AlteradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo:.
        /// </summary>
        public static string Arquivo {
            get {
                return ResourceManager.GetString("Arquivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro foi cadastrado com sucesso..
        /// </summary>
        public static string CadastradoSucesso {
            get {
                return ResourceManager.GetString("CadastradoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Obrigatório..
        /// </summary>
        public static string CampoObrigatorio {
            get {
                return ResourceManager.GetString("CampoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancela.
        /// </summary>
        public static string Cancela {
            get {
                return ResourceManager.GetString("Cancela", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente:.
        /// </summary>
        public static string Cliente {
            get {
                return ResourceManager.GetString("Cliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ:.
        /// </summary>
        public static string CNPJ {
            get {
                return ResourceManager.GetString("CNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Senha:.
        /// </summary>
        public static string ConfirmarSenha {
            get {
                return ResourceManager.GetString("ConfirmarSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF:.
        /// </summary>
        public static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor entre com um e-mail válido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Contratada:.
        /// </summary>
        public static string EmpresaContratada {
            get {
                return ResourceManager.GetString("EmpresaContratada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa Contratante:.
        /// </summary>
        public static string EmpresaContratante {
            get {
                return ResourceManager.GetString("EmpresaContratante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço:.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estacionamento:.
        /// </summary>
        public static string Estacionamento {
            get {
                return ResourceManager.GetString("Estacionamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro foi excluido com sucesso..
        /// </summary>
        public static string ExcluidoSucesso {
            get {
                return ResourceManager.GetString("ExcluidoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo deve ser uma data válida..
        /// </summary>
        public static string FieldMustBeDate {
            get {
                return ResourceManager.GetString("FieldMustBeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo deve ser um número..
        /// </summary>
        public static string FieldMustBeNumeric {
            get {
                return ResourceManager.GetString("FieldMustBeNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar ?.
        /// </summary>
        public static string Lembrar {
            get {
                return ResourceManager.GetString("Lembrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marca:.
        /// </summary>
        public static string Marca {
            get {
                return ResourceManager.GetString("Marca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelo:.
        /// </summary>
        public static string Modelo {
            get {
                return ResourceManager.GetString("Modelo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse registro não pode ser deletado, pois esta sendo relacionados em outro local..
        /// </summary>
        public static string MPAlertaNaoPodeDeletar {
            get {
                return ResourceManager.GetString("MPAlertaNaoPodeDeletar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome:.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil:.
        /// </summary>
        public static string Perfil {
            get {
                return ResourceManager.GetString("Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissões:.
        /// </summary>
        public static string Permissoes {
            get {
                return ResourceManager.GetString("Permissoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Placa Carrro:.
        /// </summary>
        public static string PlacaCarro {
            get {
                return ResourceManager.GetString("PlacaCarro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato do campo é Inválida..
        /// </summary>
        public static string PropertyValueInvalid {
            get {
                return ResourceManager.GetString("PropertyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo é obrigatório..
        /// </summary>
        public static string PropertyValueRequired {
            get {
                return ResourceManager.GetString("PropertyValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade Vagas.
        /// </summary>
        public static string QtdVagas {
            get {
                return ResourceManager.GetString("QtdVagas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro solicitado não foi encontrado ou não existe..
        /// </summary>
        public static string RegistroNaoEncontrado {
            get {
                return ResourceManager.GetString("RegistroNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo só pode ter letras, múmeros e “/”, “.”, “_”, “&amp;”, “+”, “$”, “@”..
        /// </summary>
        public static string RequisitoSenha {
            get {
                return ResourceManager.GetString("RequisitoSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha:.
        /// </summary>
        public static string Senha {
            get {
                return ResourceManager.GetString("Senha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo só pode ter um máximo de {0} caracteres..
        /// </summary>
        public static string TamanhoMaximo {
            get {
                return ResourceManager.GetString("TamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket:.
        /// </summary>
        public static string Ticket {
            get {
                return ResourceManager.GetString("Ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Serviço:.
        /// </summary>
        public static string TipoServico {
            get {
                return ResourceManager.GetString("TipoServico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor:.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor:.
        /// </summary>
        public static string ValorServico {
            get {
                return ResourceManager.GetString("ValorServico", resourceCulture);
            }
        }
    }
}
